name : First Workflow

on : push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5
            - name: Welcome Message
              run: echo "Hello, welcome to your first GitHub Actions workflow!"

            - name: List all the files
              run: ls 
            
            - name: Read the file
              run: cat README.md