name : generate ASCII art

on: push  

jobs:
    generate-ascii:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Excecuting the shellscript command
              run: |
                 chmod +x ./.github/workflows/ascii-script.sh
                 ./.github/workflows/ascii-script.sh

            